EVENT_TYPE_AGGREGATION_INFORMATION_PHISHING_SCHEMES = "aggregation-information-phishing-schemes"
EVENT_TYPE_BENIGN = "benign"
EVENT_TYPE_BLOCKED = "blocked"
EVENT_TYPE_BRUTE_FORCE_ATTEMPT = "brute-force-attempt"
EVENT_TYPE_C_AND_C_SERVER_HOSTING = "c&c-server-hosting"
EVENT_TYPE_COMPROMISED_SYSTEM = "compromised-system"
EVENT_TYPE_CONFIRMED = "confirmed"
EVENT_TYPE_CONNECTION_MALWARE_PORT = "connection-malware-port"
EVENT_TYPE_CONNECTION_MALWARE_SYSTEM = "connection-malware-system"
EVENT_TYPE_CONTENT_FORBIDDEN_BY_LAW = "content-forbidden-by-law"
EVENT_TYPE_CONTROL_SYSTEM_BYPASS = "control-system-bypass"
EVENT_TYPE_COPYRIGHTED_CONTENT = "copyrighted-content"
EVENT_TYPE_DATA_EXFILTRATION = "data-exfiltration"
EVENT_TYPE_DEFERRED = "deferred"
EVENT_TYPE_DELETION_INFORMATION = "deletion-information"
EVENT_TYPE_DENIAL_OF_SERVICE = "denial-of-service"
EVENT_TYPE_DESTRUCTION = "destruction"
EVENT_TYPE_DICTIONARY_ATTACK_ATTEMPT = "dictionary-attack-attempt"
EVENT_TYPE_DISCARDED = "discarded"
EVENT_TYPE_DISRUPTION_DATA_TRANSMISSION = "disruption-data-transmission"
EVENT_TYPE_DISSEMINATION_MALWARE_EMAIL = "dissemination-malware-email"
EVENT_TYPE_DISSEMINATION_PHISHING_EMAILS = "dissemination-phishing-emails"
EVENT_TYPE_DNS_CACHE_POISONING = "dns-cache-poisoning"
EVENT_TYPE_DNS_LOCAL_RESOLVER_HIJACKING = "dns-local-resolver-hijacking"
EVENT_TYPE_DNS_SPOOFING_REGISTERED = "dns-spoofing-registered"
EVENT_TYPE_DNS_REBINDING = "dns-rebinding"
EVENT_TYPE_DNS_SERVER_COMPROMISE = "dns-server-compromise"
EVENT_TYPE_DNS_SPOOFING_UNREGISTERED = "dns-spoofing-unregistered"
EVENT_TYPE_DNS_STUB_RESOLVER_HIJACKING = "dns-stub-resolver-hijacking"
EVENT_TYPE_DNS_ZONE_TRANSFER = "dns-zone-transfer"
EVENT_TYPE_DOMAIN_NAME_COMPROMISE = "domain-name-compromise"
EVENT_TYPE_DUPLICATE = "duplicate"
EVENT_TYPE_EMAIL_FLOODING = "email-flooding"
EVENT_TYPE_EQUIPMENT_LOSS = "equipment-loss"
EVENT_TYPE_EQUIPMENT_THEFT = "equipment-theft"
EVENT_TYPE_EXPOIT = "exploit"
EVENT_TYPE_EXPLOIT_ATTEMPT = "exploit-attempt"
EVENT_TYPE_EXPLOIT_FRAMEWORK_EXHAUSTING_RESOURCES = "exploit-framework-exhausting-resources"
EVENT_TYPE_EXPLOIT_TOOL_EXHAUSTING_RESOURCES = "exploit-tool-exhausting-resources"
EVENT_TYPE_FAILED = "failed"
EVENT_TYPE_FILE_INCLUSION = "file-inclusion"
EVENT_TYPE_FILE_INCLUSION_ATTEMPT = "file-inclusion-attempt"
EVENT_TYPE_HOSTING_MALWARE_WEBPAGE = "hosting-malware-webpage"
EVENT_TYPE_HOSTING_PHISHING_SITES = "hosting-phishing-sites"
EVENT_TYPE_ILLEGITIMATE_USE_NAME = "illegitimate-use-name"
EVENT_TYPE_ILLEGITIMATE_USE_RESOURCES = "illegitimate-use-resources"
EVENT_TYPE_INFECTED_BY_KNOWN_MALWARE = "infected-by-known-malware"
EVENT_TYPE_INSUFFICIENT_DATA = "insufficient-data"
EVENT_TYPE_KNOWN_MALWARE = "known-malware"
EVENT_TYPE_LAME_DELEGATIONS = "lame-delegations"
EVENT_TYPE_MAJOR = "major"
EVENT_TYPE_MODIFICATION_INFORMATION = "modification-information"
EVENT_TYPE_MISCONFIGURATION = "misconfiguration"
EVENT_TYPE_NATURAL = "natural"
EVENT_TYPE_NEGOTIATION = "negotiation"
EVENT_TYPE_NETWORK_SCANNING = "network-scanning"
EVENT_TYPE_NO_APT = "no-apt"
EVENT_TYPE_PACKET_FLOOD = "packet-flood"
EVENT_TYPE_PASSWORD_CRACKING_ATTEMPT = "password-cracking-attempt"
EVENT_TYPE_POLICY_VIOLATION = "policy-violation"
EVENT_TYPE_RANSOMWARE = "ransomware"
EVENT_TYPE_RANSOMWARE_PAYMENT = "ransomware-payment"
EVENT_TYPE_REFUTED = "refuted"
EVENT_TYPE_SCAN_PROBE = "scan-probe"
EVENT_TYPE_SILENTLY_DISCARDED = "silently-discarded"
EVENT_TYPE_SUPPLY_CHAIN_CUSTOMER = "supply-chain-customer"
EVENT_TYPE_SUPPLY_CHAIN_VENDOR = "supply-chain-vendor"
EVENT_TYPE_SPAM = "spam"
EVENT_TYPE_SQL_INJECTION = "sql-injection"
EVENT_TYPE_SQL_INJECTION_ATTEMPT = "sql-injection-attempt"
EVENT_TYPE_SUCCESSFUL = "successful"
EVENT_TYPE_SYSTEM_PROBE = "system-probe"
EVENT_TYPE_THEFT_ACCESS_CREDENTIALS = "theft-access-credentials"
EVENT_TYPE_UNATTRIBUTED = "unattributed"
EVENT_TYPE_UNAUTHORIZED_ACCESS_INFORMATION = "unauthorized-access-information"
EVENT_TYPE_UNAUTHORIZED_ACCESS_SYSTEM = "unauthorized-access-system"
EVENT_TYPE_UNAUTHORIZED_EQUIPMENT = "unauthorized-equipment"
EVENT_TYPE_UNAUTHORIZED_RELEASE = "unauthorized-release"
EVENT_TYPE_UNAUTHORIZED_USE = "unauthorized-use"
EVENT_TYPE_UNDETERMINED = "undetermined"
EVENT_TYPE_UNINTENTIONAL = "unintentional"
EVENT_TYPE_UNKNOWN_APT = "unknown-apt"
EVENT_TYPE_UNSPECIFIED = "unspecified"
EVENT_TYPE_VANDALISM = "vandalism"
EVENT_TYPE_WIRETAPPING = "wiretapping"
EVENT_TYPE_WORM_SPREADING = "worm-spreading"
EVENT_TYPE_XSS = "xss"
EVENT_TYPE_XSS_ATTEMPT = "xss-attempt"


EVENT_TYPE = [
    EVENT_TYPE_AGGREGATION_INFORMATION_PHISHING_SCHEMES,
    EVENT_TYPE_BENIGN,
    EVENT_TYPE_BLOCKED,
    EVENT_TYPE_BRUTE_FORCE_ATTEMPT,
    EVENT_TYPE_C_AND_C_SERVER_HOSTING,
    EVENT_TYPE_COMPROMISED_SYSTEM,
    EVENT_TYPE_CONFIRMED,
    EVENT_TYPE_CONNECTION_MALWARE_PORT,
    EVENT_TYPE_CONNECTION_MALWARE_SYSTEM,
    EVENT_TYPE_CONTENT_FORBIDDEN_BY_LAW,
    EVENT_TYPE_CONTROL_SYSTEM_BYPASS,
    EVENT_TYPE_COPYRIGHTED_CONTENT,
    EVENT_TYPE_DATA_EXFILTRATION,
    EVENT_TYPE_DEFERRED,
    EVENT_TYPE_DELETION_INFORMATION,
    EVENT_TYPE_DENIAL_OF_SERVICE,
    EVENT_TYPE_DESTRUCTION,
    EVENT_TYPE_DICTIONARY_ATTACK_ATTEMPT,
    EVENT_TYPE_DISCARDED,
    EVENT_TYPE_DISRUPTION_DATA_TRANSMISSION,
    EVENT_TYPE_DISSEMINATION_MALWARE_EMAIL,
    EVENT_TYPE_DISSEMINATION_PHISHING_EMAILS,
    EVENT_TYPE_DNS_CACHE_POISONING,
    EVENT_TYPE_DNS_LOCAL_RESOLVER_HIJACKING,
    EVENT_TYPE_DNS_SPOOFING_REGISTERED,
    EVENT_TYPE_DNS_REBINDING,
    EVENT_TYPE_DNS_SERVER_COMPROMISE,
    EVENT_TYPE_DNS_SPOOFING_UNREGISTERED,
    EVENT_TYPE_DNS_STUB_RESOLVER_HIJACKING,
    EVENT_TYPE_DNS_ZONE_TRANSFER,
    EVENT_TYPE_DOMAIN_NAME_COMPROMISE,
    EVENT_TYPE_DUPLICATE,
    EVENT_TYPE_EMAIL_FLOODING,
    EVENT_TYPE_EQUIPMENT_LOSS,
    EVENT_TYPE_EQUIPMENT_THEFT,
    EVENT_TYPE_EXPOIT,
    EVENT_TYPE_EXPLOIT_ATTEMPT,
    EVENT_TYPE_EXPLOIT_FRAMEWORK_EXHAUSTING_RESOURCES,
    EVENT_TYPE_EXPLOIT_TOOL_EXHAUSTING_RESOURCES,
    EVENT_TYPE_FAILED,
    EVENT_TYPE_FILE_INCLUSION,
    EVENT_TYPE_FILE_INCLUSION_ATTEMPT,
    EVENT_TYPE_HOSTING_MALWARE_WEBPAGE,
    EVENT_TYPE_HOSTING_PHISHING_SITES,
    EVENT_TYPE_ILLEGITIMATE_USE_NAME,
    EVENT_TYPE_ILLEGITIMATE_USE_RESOURCES,
    EVENT_TYPE_INFECTED_BY_KNOWN_MALWARE,
    EVENT_TYPE_INSUFFICIENT_DATA,
    EVENT_TYPE_KNOWN_MALWARE,
    EVENT_TYPE_LAME_DELEGATIONS,
    EVENT_TYPE_MAJOR,
    EVENT_TYPE_MODIFICATION_INFORMATION,
    EVENT_TYPE_MISCONFIGURATION,
    EVENT_TYPE_NATURAL,
    EVENT_TYPE_NEGOTIATION,
    EVENT_TYPE_NETWORK_SCANNING,
    EVENT_TYPE_NO_APT,
    EVENT_TYPE_PACKET_FLOOD,
    EVENT_TYPE_PASSWORD_CRACKING_ATTEMPT,
    EVENT_TYPE_POLICY_VIOLATION,
    EVENT_TYPE_RANSOMWARE,
    EVENT_TYPE_RANSOMWARE_PAYMENT,
    EVENT_TYPE_REFUTED,
    EVENT_TYPE_SCAN_PROBE,
    EVENT_TYPE_SILENTLY_DISCARDED,
    EVENT_TYPE_SUPPLY_CHAIN_CUSTOMER,
    EVENT_TYPE_SUPPLY_CHAIN_VENDOR,
    EVENT_TYPE_SPAM,
    EVENT_TYPE_SQL_INJECTION,
    EVENT_TYPE_SQL_INJECTION_ATTEMPT,
    EVENT_TYPE_SUCCESSFUL,
    EVENT_TYPE_SYSTEM_PROBE,
    EVENT_TYPE_THEFT_ACCESS_CREDENTIALS,
    EVENT_TYPE_UNATTRIBUTED,
    EVENT_TYPE_UNAUTHORIZED_ACCESS_INFORMATION,
    EVENT_TYPE_UNAUTHORIZED_ACCESS_SYSTEM,
    EVENT_TYPE_UNAUTHORIZED_EQUIPMENT,
    EVENT_TYPE_UNAUTHORIZED_RELEASE,
    EVENT_TYPE_UNAUTHORIZED_USE,
    EVENT_TYPE_UNDETERMINED,
    EVENT_TYPE_UNINTENTIONAL,
    EVENT_TYPE_UNKNOWN_APT,
    EVENT_TYPE_UNSPECIFIED,
    EVENT_TYPE_VANDALISM,
    EVENT_TYPE_WIRETAPPING,
    EVENT_TYPE_WORM_SPREADING,
    EVENT_TYPE_XSS,
    EVENT_TYPE_XSS_ATTEMPT
]


RECOVERABILITY_EXTENDED = 'extended'
RECOVERABILITY_NOT_APPLICABLE = 'not-applicable'
RECOVERABILITY_NOT_RECOVERABLE = 'not-recoverable'
RECOVERABILITY_REGULAR = 'regular'
RECOVERABILITY_SUPPLEMENTED = 'supplemented'


RECOVERABILITY = [
    RECOVERABILITY_EXTENDED,
    RECOVERABILITY_NOT_APPLICABLE,
    RECOVERABILITY_NOT_RECOVERABLE,
    RECOVERABILITY_REGULAR,
    RECOVERABILITY_SUPPLEMENTED
]


# Timestamp fidelity
TIMESTAMP_FIDELITY_DAY = 'day'
TIMESTAMP_FIDELITY_HOUR = 'hour'
TIMESTAMP_FIDELITY_MINUTE = 'minute'
TIMESTAMP_FIDELITY_MONTH = 'month'
TIMESTAMP_FIDELITY_SECOND = 'second'
TIMESTAMP_FIDELITY_YEAR = 'year'


TIMESTAMP_FIDELITY = [
    TIMESTAMP_FIDELITY_DAY,
    TIMESTAMP_FIDELITY_HOUR,
    TIMESTAMP_FIDELITY_MINUTE,
    TIMESTAMP_FIDELITY_MONTH,
    TIMESTAMP_FIDELITY_SECOND,
    TIMESTAMP_FIDELITY_YEAR
]


INCIDENT_DETERMINATION_BLOCKED = 'blocked'
INCIDENT_DETERMINATION_CONFIRMED = 'confirmed'
INCIDENT_DETERMINATION_FAILED_ATTEMPT = 'failed-attempt'
INCIDENT_DETERMINATION_FALSE_POSITIVE = 'false-positive'
INCIDENT_DETERMINATION_SUSPECTED = 'suspected'


INCIDENT_DETERMINATION = [
    INCIDENT_DETERMINATION_BLOCKED,
    INCIDENT_DETERMINATION_CONFIRMED,
    INCIDENT_DETERMINATION_FAILED_ATTEMPT,
    INCIDENT_DETERMINATION_FALSE_POSITIVE,
    INCIDENT_DETERMINATION_SUSPECTED
]


CONFIDENTIALITY_LOSS_CONFIRMED_LOSS = 'confirmed-loss'
CONFIDENTIALITY_LOSS_CONTAINED = 'contained'
CONFIDENTIALITY_LOSS_EXPLOITED_LOSS = 'exploited-loss'
CONFIDENTIALITY_LOSS_NONE = 'none'
CONFIDENTIALITY_LOSS_SUSPECTED_LOSS = 'suspected-loss'


CONFIDENTIALITY_LOSS = [
    CONFIDENTIALITY_LOSS_CONFIRMED_LOSS,
    CONFIDENTIALITY_LOSS_CONTAINED,
    CONFIDENTIALITY_LOSS_EXPLOITED_LOSS,
    CONFIDENTIALITY_LOSS_NONE,
    CONFIDENTIALITY_LOSS_SUSPECTED_LOSS,
]


INFORMATION_TYPE_CLASSIFIED_MATERIAL = 'classified-material'
INFORMATION_TYPE_COMMUNICATION = 'communication'
INFORMATION_TYPE_CREDENTIALS_ADMIN = 'credentials-admin'
INFORMATION_TYPE_CREDENTIALS_USER = 'credentials-user'
INFORMATION_TYPE_FINANCIAL = 'financial'
INFORMATION_TYPE_LEGAL = 'legal'
INFORMATION_TYPE_PAYMENT = 'payment'
INFORMATION_TYPE_PHI = 'phi'
INFORMATION_TYPE_PII = 'pii'
INFORMATION_TYPE_PROPRIETARY = 'proprietary'
INFORMATION_TYPE_SYSTEM = 'system'


INFORMATION_TYPE = [
    INFORMATION_TYPE_CLASSIFIED_MATERIAL,
    INFORMATION_TYPE_COMMUNICATION,
    INFORMATION_TYPE_CREDENTIALS_ADMIN,
    INFORMATION_TYPE_CREDENTIALS_USER,
    INFORMATION_TYPE_FINANCIAL,
    INFORMATION_TYPE_LEGAL,
    INFORMATION_TYPE_PAYMENT,
    INFORMATION_TYPE_PHI,
    INFORMATION_TYPE_PII,
    INFORMATION_TYPE_PROPRIETARY,
    INFORMATION_TYPE_SYSTEM
]


INTEGRITY_ALTERATION_POTENTIAL_DESTRUCTION = "potential-destruction"
INTEGRITY_ALTERATION_POTENTIAL_MODIFICATION = "potential-modification"
INTEGRITY_ALTERATION_PARTIAL_DESTRUCTION = "partial-destruction"
INTEGRITY_ALTERATION_PARTIAL_MODIFICATION = "partial-modification"
INTEGRITY_ALTERATION_FULL_DESTRUCTION = "full-destruction"
INTEGRITY_ALTERATION_FULL_MODIFICATION = "full-modification"
INTEGRITY_ALTERATION_NONE = "none"


INTEGRITY_ALTERATION = [
    INTEGRITY_ALTERATION_POTENTIAL_DESTRUCTION,
    INTEGRITY_ALTERATION_POTENTIAL_MODIFICATION,
    INTEGRITY_ALTERATION_PARTIAL_DESTRUCTION,
    INTEGRITY_ALTERATION_PARTIAL_MODIFICATION,
    INTEGRITY_ALTERATION_FULL_DESTRUCTION,
    INTEGRITY_ALTERATION_FULL_MODIFICATION,
    INTEGRITY_ALTERATION_NONE
]


ECONOMIC_IMPACT_ASSET_AND_FRAUD = 'asset-and-fraud'
ECONOMIC_IMPACT_BRAND_DAMAGE = 'brand-damage'
ECONOMIC_IMPACT_BUSINESS_DISRUPTION = 'business-disruption'
ECONOMIC_IMPACT_COMPETITIVE_ADVANTAGE = 'competitive-advantage'
ECONOMIC_IMPACT_LEGAL_AND_REGULATORY = 'legal-and-regulatory'
ECONOMIC_IMPACT_OPERATING_COSTS = 'operating-costs'
ECONOMIC_IMPACT_RANSOM_DEMAND = 'ransom-demand'
ECONOMIC_IMPACT_RANSOM_PAYMENT = 'ransom-payment'
ECONOMIC_IMPACT_RESPONSE_AND_RECOVERY = 'response-and-recovery'
ECONOMIC_IMPACT_UNCATEGORIZED = 'uncategorized'


ECONOMIC_IMPACT = [
    ECONOMIC_IMPACT_ASSET_AND_FRAUD,
    ECONOMIC_IMPACT_BRAND_DAMAGE,
    ECONOMIC_IMPACT_BUSINESS_DISRUPTION,
    ECONOMIC_IMPACT_COMPETITIVE_ADVANTAGE,
    ECONOMIC_IMPACT_LEGAL_AND_REGULATORY,
    ECONOMIC_IMPACT_OPERATING_COSTS,
    ECONOMIC_IMPACT_RANSOM_DEMAND,
    ECONOMIC_IMPACT_RANSOM_PAYMENT,
    ECONOMIC_IMPACT_RESPONSE_AND_RECOVERY,
    ECONOMIC_IMPACT_UNCATEGORIZED
]


PHYSICAL_IMPACT_DAMAGED_FUNCTIONAL = 'damaged-functional'
PHYSICAL_IMPACT_DAMAGED_NONFUNCTIONAL = 'damaged-nonfunctional'
PHYSICAL_IMPACT_DESTRUCTION = 'destruction'
PHYSICAL_IMPACT_NONE = 'none'
PHYSICAL_IMPACT_UNKNOWN = 'unknown'


PHYSICAL_IMPACT = [
    PHYSICAL_IMPACT_DAMAGED_FUNCTIONAL,
    PHYSICAL_IMPACT_DAMAGED_NONFUNCTIONAL,
    PHYSICAL_IMPACT_DESTRUCTION,
    PHYSICAL_IMPACT_NONE,
    PHYSICAL_IMPACT_UNKNOWN
]


TRACEABILITY_IMPACT_ACCOUNTABILITY_LOST = 'accountability-lost'
TRACEABILITY_IMPACT_PARTIAL_ACCOUNTABILITY = 'partial-accountability'
TRACEABILITY_IMPACT_PROVABLE_ACCOUNTABILITY = 'provable-accountability'


TRACEABILITY_IMPACT = [
    TRACEABILITY_IMPACT_ACCOUNTABILITY_LOST,
    TRACEABILITY_IMPACT_PARTIAL_ACCOUNTABILITY,
    TRACEABILITY_IMPACT_PROVABLE_ACCOUNTABILITY
]


ASSET_TYPE_BUILDING_DOORS = 'building-doors'
ASSET_TYPE_BUILDING_WINDOWS = 'building-windows'
ASSET_TYPE_BUILDINGS = 'buildings'
ASSET_TYPE_COMPUTERS_MOBILE = 'computers-mobile'
ASSET_TYPE_COMPUTERS_PERSONAL = 'computers-personal'
ASSET_TYPE_COMPUTERS_SERVER = 'computers-server'
ASSET_TYPE_ENVIRONMENT = 'environment'
ASSET_TYPE_ICS_ACTUATOR = 'ics-actuator'
ASSET_TYPE_ICS_ENGINEERING_WORKSTATION = 'ics-engineering-workstation'
ASSET_TYPE_ICS_HISTORIAN = 'ics-historian'
ASSET_TYPE_ICS_HMI = 'ics-hmi'
ASSET_TYPE_ICS_OTHER = 'ics-other'
ASSET_TYPE_ICS_PLC = 'ics-plc'
ASSET_TYPE_ICS_SAFETY_SYSTEM = 'ics-safety-system'
ASSET_TYPE_ICS_SENSOR = 'ics-sensor'
ASSET_TYPE_INVENTORY = 'inventory'
ASSET_TYPE_NETWORK_DEVICE = 'network-device'
ASSET_TYPE_PRIVATE_INFRASTRUCTURE = 'private-infrastructure'
ASSET_TYPE_PUBLIC_INFRASTRUCTURE = 'public-infrastructure'
ASSET_TYPE_SECURITY_CONTAINERS = 'security-containers'
ASSET_TYPE_VEHICLES = 'vehicles'


ASSET_TYPE = [
    ASSET_TYPE_BUILDING_DOORS,
    ASSET_TYPE_BUILDING_WINDOWS,
    ASSET_TYPE_BUILDINGS,
    ASSET_TYPE_COMPUTERS_MOBILE,
    ASSET_TYPE_COMPUTERS_PERSONAL,
    ASSET_TYPE_COMPUTERS_SERVER,
    ASSET_TYPE_ENVIRONMENT,
    ASSET_TYPE_ICS_ACTUATOR,
    ASSET_TYPE_ICS_ENGINEERING_WORKSTATION,
    ASSET_TYPE_ICS_HISTORIAN,
    ASSET_TYPE_ICS_HMI,
    ASSET_TYPE_ICS_OTHER,
    ASSET_TYPE_ICS_PLC,
    ASSET_TYPE_ICS_SAFETY_SYSTEM,
    ASSET_TYPE_ICS_SENSOR,
    ASSET_TYPE_INVENTORY,
    ASSET_TYPE_NETWORK_DEVICE,
    ASSET_TYPE_PRIVATE_INFRASTRUCTURE,
    ASSET_TYPE_PUBLIC_INFRASTRUCTURE,
    ASSET_TYPE_SECURITY_CONTAINERS,
    ASSET_TYPE_VEHICLES
]


EXTERNAL_IMPACT_ECONOMIC = 'economic'
EXTERNAL_IMPACT_EMERGENCY_SERVICES = 'emergency-services'
EXTERNAL_IMPACT_FOREIGN_RELATIONS = 'foreign-relations'
EXTERNAL_IMPACT_NATIONAL_SECURITY = 'national-security'
EXTERNAL_IMPACT_PUBLIC_CONFIDENCE = 'public-confidence'
EXTERNAL_IMPACT_PUBLIC_HEALTH = 'public-health'
EXTERNAL_IMPACT_PUBLIC_SAFETY = 'public-safety'


EXTERNAL_IMPACT = [
    EXTERNAL_IMPACT_ECONOMIC,
    EXTERNAL_IMPACT_EMERGENCY_SERVICES,
    EXTERNAL_IMPACT_FOREIGN_RELATIONS,
    EXTERNAL_IMPACT_NATIONAL_SECURITY,
    EXTERNAL_IMPACT_PUBLIC_CONFIDENCE,
    EXTERNAL_IMPACT_PUBLIC_HEALTH,
    EXTERNAL_IMPACT_PUBLIC_SAFETY
]


DETECTION_METHODS_AUTOMATED_TOOL = "automated-tool"
DETECTION_METHODS_COMMERCIAL_SOLUTION = "commercial-solution"
DETECTION_METHODS_EXTERNAL_NOTIFICATION = "external-notification"
DETECTION_METHODS_HUMAN_REVIEW = "human-review"
DETECTION_METHODS_MESSAGE_FROM_ATTACKER = "message-from-attacker"
DETECTION_METHODS_PROPRIETARY_SOLUTION = "proprietary-solution"
DETECTION_METHODS_SYSTEM_OUTAGE = "system-outage"
DETECTION_METHODS_USER_REPORTING = "user-reporting"


DETECTION_METHODS = [
    DETECTION_METHODS_AUTOMATED_TOOL,
    DETECTION_METHODS_COMMERCIAL_SOLUTION,
    DETECTION_METHODS_EXTERNAL_NOTIFICATION,
    DETECTION_METHODS_HUMAN_REVIEW,
    DETECTION_METHODS_MESSAGE_FROM_ATTACKER,
    DETECTION_METHODS_PROPRIETARY_SOLUTION,
    DETECTION_METHODS_SYSTEM_OUTAGE,
    DETECTION_METHODS_USER_REPORTING
]


INCIDENT_INVESTIGATION_CLOSED = "closed"
INCIDENT_INVESTIGATION_NEW = "new"
INCIDENT_INVESTIGATION_OPEN = "open"


INCIDENT_INVESTIGATION = [
    INCIDENT_INVESTIGATION_CLOSED,
    INCIDENT_INVESTIGATION_NEW,
    INCIDENT_INVESTIGATION_OPEN
]


EVENT_STATUS_ONGOING = "ongoing"
EVENT_STATUS_OCCURRED = "occurred"
EVENT_STATUS_NOT_OCCURRED = "not-occurred"
EVENT_STATUS_PENDING = "pending"
EVENT_STATUS_UNDETERMINED = "undetermined"


EVENT_STATUS = [
    EVENT_STATUS_ONGOING,
    EVENT_STATUS_OCCURRED,
    EVENT_STATUS_NOT_OCCURRED,
    EVENT_STATUS_PENDING,
    EVENT_STATUS_UNDETERMINED
]


ACTIVITY_CONDITION_OPTIONAL = 'optional'
ACTIVITY_CONDITION_REQUIRED = 'required'
ACTIVITY_CONDITION_UNKNOWN = "unknown"


ACTIVITY_CONDITION = [
    ACTIVITY_CONDITION_OPTIONAL,
    ACTIVITY_CONDITION_REQUIRED,
    ACTIVITY_CONDITION_UNKNOWN
]


ACTIVITY_TRANSITION_COMPLETION = 'completion'
ACTIVITY_TRANSITION_FAILURE = 'failure'
ACTIVITY_TRANSITION_SUCCESS = 'success'
ACTIVITY_TRANSITION_UNKNOWN = "unknown"


ACTIVITY_TRANSITION = [
    ACTIVITY_TRANSITION_COMPLETION,
    ACTIVITY_TRANSITION_FAILURE,
    ACTIVITY_TRANSITION_SUCCESS,
    ACTIVITY_TRANSITION_UNKNOWN
]


TASK_TYPE_ADMINISTRATIVE = "administrative"
TASK_TYPE_ATTRIBUTION = "attribution"
TASK_TYPE_CONTAINMENT = "containment"
TASK_TYPE_DECLARED = "declared"
TASK_TYPE_DETECTED = "detected"
TASK_TYPE_ERADICATION = "eradication"
TASK_TYPE_ESCALATED = "escalated"
TASK_TYPE_EXERCISED_CONTROL = "exercised-control"
TASK_TYPE_EXTERNAL_INTELLIGENCE = "external-intelligence"
TASK_TYPE_EXTERNAL_OUTREACH = "external-outreach"
TASK_TYPE_EXTERNAL_SUPPORT = "external-support"
TASK_TYPE_IMPLEMENTED_CONTROL = "implemented-control"
TASK_TYPE_INVESTIGATION = "investigation"
TASK_TYPE_NEGOTIATION = "negotiation"
TASK_TYPE_PLAYBOOK_EXECUTION = "playbook-execution"
TASK_TYPE_PLAYBOOK_STEP_EXECUTION = "playbook-step-execution"
TASK_TYPE_RANSOM_PAYMENT = "ransom-payment"
TASK_TYPE_RECOVERY = "recovery"
TASK_TYPE_REPORTED = "reported"
TASK_TYPE_ROUTINE_UPDATES = "routine-updates"
TASK_TYPE_VICTIM_NOTIFICATION = "victim-notification"


TASK_TYPE = [
    TASK_TYPE_ADMINISTRATIVE,
    TASK_TYPE_ATTRIBUTION,
    TASK_TYPE_CONTAINMENT,
    TASK_TYPE_DECLARED,
    TASK_TYPE_DETECTED,
    TASK_TYPE_ERADICATION,
    TASK_TYPE_ESCALATED,
    TASK_TYPE_EXERCISED_CONTROL,
    TASK_TYPE_EXTERNAL_INTELLIGENCE,
    TASK_TYPE_EXTERNAL_OUTREACH,
    TASK_TYPE_EXTERNAL_SUPPORT,
    TASK_TYPE_IMPLEMENTED_CONTROL,
    TASK_TYPE_INVESTIGATION,
    TASK_TYPE_NEGOTIATION,
    TASK_TYPE_PLAYBOOK_EXECUTION,
    TASK_TYPE_PLAYBOOK_STEP_EXECUTION,
    TASK_TYPE_RANSOM_PAYMENT,
    TASK_TYPE_RECOVERY,
    TASK_TYPE_REPORTED,
    TASK_TYPE_ROUTINE_UPDATES,
    TASK_TYPE_VICTIM_NOTIFICATION
]


TASK_OUTCOME_CANCELLED = 'cancelled'
TASK_OUTCOME_FAILED = 'failed'
TASK_OUTCOME_ONGOING = 'ongoing'
TASK_OUTCOME_PENDING = 'pending'
TASK_OUTCOME_SUCCESSFUL = 'successful'
TASK_OUTCOME_UNKNOWN = "unknown"


TASK_OUTCOME = [
    TASK_OUTCOME_CANCELLED,
    TASK_OUTCOME_FAILED,
    TASK_OUTCOME_ONGOING,
    TASK_OUTCOME_PENDING,
    TASK_OUTCOME_SUCCESSFUL,
    TASK_OUTCOME_UNKNOWN
]


STATE_CHANGE_TYPE_CAUSED = 'caused'
STATE_CHANGE_TYPE_CONTRIBUTED_TO = 'contributed-to'
STATE_CHANGE_TYPE_INPUT = 'input'
STATE_CHANGE_TYPE_MITIGATED = 'mitigated'
STATE_CHANGE_TYPE_OUTPUT = 'output'
STATE_CHANGE_TYPE_RESOLVED = 'resolved'


STATE_CHANGE_TYPE = [
    STATE_CHANGE_TYPE_CAUSED,
    STATE_CHANGE_TYPE_CONTRIBUTED_TO,
    STATE_CHANGE_TYPE_INPUT,
    STATE_CHANGE_TYPE_MITIGATED,
    STATE_CHANGE_TYPE_OUTPUT,
    STATE_CHANGE_TYPE_RESOLVED
]
