MAY = 'may'
MUST = 'must'
MUST_NOT = 'must-not'

IEP_ACTION_NONE = 'none'
IEP_ACTION_CONTACT_FOR_INSTRUCTION = 'contact-for-instruction'
IEP_ACTION_INTERNALLY_VISIBLE_ACTIONS = 'internally-visible-actions'
IEP_ACTION_EXTERNALLY_VISIBLE_INDIRECT_ACTIONS = 'externally-visible-indirect-actions'
IEP_ACTION_EXTERNALLY_VISIBLE_DIRECT_ACTIONS = 'externally-visible-direct-actions'

IEP_PERMITTED_ACTIONS = [
    IEP_ACTION_NONE,
    IEP_ACTION_CONTACT_FOR_INSTRUCTION,
    IEP_ACTION_INTERNALLY_VISIBLE_ACTIONS,
    IEP_ACTION_EXTERNALLY_VISIBLE_INDIRECT_ACTIONS,
    IEP_ACTION_EXTERNALLY_VISIBLE_DIRECT_ACTIONS
]
